networks:
  hrmappnetwork:
services:
  hrmappDB:
    container_name: HRMappDBContainer
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Linh172901@@
    networks: 
      - hrmappnetwork
      
  hrmapp.web:
    container_name: hrmappContainer
    image: hrmapp.web
    ports:
      - 8001:80
    build:
      context: .
      dockerfile: src/HRMapp.Web/Dockerfile
    depends_on: 
      - hrmappDB
    networks:
      - hrmappnetwork